single_border = " ---------------------- ---------------------- --------------------- ---------------------- --------------------- "
new_line = " \n"
header_instances = "| Region               | Instance ID          | Instance Name       | Instance Type        | Status              |"
double_border = " ====================== ====================== ===================== ====================== ===================== "
region = "*** Region: "
instance_id = "Instance ID: "
instance_name = "Instance Name: "
instance_type = "Instance Type: "
status = "Status: "
instances_running_per_region = "Instances Running in this Region: "
INSTANCES_PATH = "./AllInstances.json"
SUMMARY_PATH = "./InstanceSummary.json"
instance_title = "*LIST OF INSTANCES*"
summary_title = "*SUMMARY OF INSTANCES ACROSS REGIONS*"
single_border_unbroken = "-------------------------------------------------------------"
double_border_unbroken = "======================================================"
backticks = "```"
HOME = "/Users/s.sathyakumari/Downloads/projects/aws_botmon"